num_tries_to_find_loop = 0  # 5
num_tries_to_add_link = 5
young_age_threshold = 10
young_fitness_bonus = 1.3
old_age_threshold = 50
old_age_penalty = 0.7
survival_rate = 0.2
crossover_rate = 0.7
max_permitted_neurons = 50
chance_to_add_neuron = 0.08
num_tries_to_find_old_link = 5
chance_to_add_link = 0.1
chance_to_add_recurrent_link = 0  # 0.05
mutation_rate = 0.2
probability_of_weight_replacement = 0.1
max_weight_perturbation = 0.5
activation_mutation_rate = 0.1
max_activation_perturbation = 0.1
population_size = 100
gens_allowed_with_no_improvement = 15
best_sweepers_num = 4
compatibility_threshold = 0.26
max_number_of_species = 10
epsilon = 0.95
max_generation = 50

# score multipliers for speciation
disjoint_multiplier = 1
excess_multiplier = 1
matched_multiplier = 0.4
